# GitHub Actions Example: Knitr with renv
# Here is a complete example of a GitHub Action that installs R and R package dependencies from renv.lock, and Pyton and Python packages dependencies from requirements.txt
# then executes code and renders output to GitHub Pages

name: "Quarto Publish to Github Pages"

on:
  workflow_dispatch:
  push:
    branches: main
  # schedule:
  #   - cron: '0 9 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
          use-public-rspm: true
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        # with:
        #   cache-version: 1

      # - name: Manually Install packages from CRAN
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages: |
      #       any::tidyverse
      #       any::gt
      #       any::reticulate

      # - name: Manually install other R Packages not in CRAN
      #   run: |
      #     install.packages("remotes")
      #     remotes::install_github("mohitshrestha/automaton")
      #   shell: Rscript {0}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'

      - name: Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r py_requirements.txt

      - name: Render and Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}